### PR TITLE
Add method for next filter change date

### PR DESCRIPTION
**Pull request by slovdahl**
Inspired by https://github.com/home-assistant/core/pull/66443#discussion_r805352225.

### CODE REVIEW

**Comment by yozik04** [comment]
Great!

**Comment by andre-richter** [comment]
Would it not have been better to implement the function in the way `get_uuid` is implemented? Meaning that it takes an already fetched metrics dict?

Then we could use this function on the local metric cache in ValloxState as we do for UUID:
https://github.com/home-assistant/core/blob/98ae7e106ca8e9fd12fe3b653e128ffbee8033c5/homeassistant/components/vallox/__init__.py#L130

**Comment by yozik04** [comment]
If we query it once a day then it is totally fine.

**Comment by yozik04** [comment]
@andre-richter But I see your point. Makes sense as well.

**Comment by yozik04** [comment]
@andre-richter Here it is: https://github.com/yozik04/vallox_websocket_api/blob/6d6c0ecaaa77e64ae3990afc2d5ac28925f4c02a/vallox_websocket_api/vallox.py#L97

**Comment by yozik04** [comment]
Available in 2.11.0

**Comment by andre-richter** [comment]
Awesome 👏 🚀

**Comment by slovdahl** [comment]
Awesome, thanks @andre-richter and @yozik04!

**Pull request merged**
