### PR TITLE
New method fetch_metric_data() -> MetricData

### PR DESCRIPTION
**Pull request by yozik04**
The plan is to replace all `fetch_metric` calls with `fetch_metric_data` that will return new `MetricData` class instance.
`MetricData` class works the same way as dictionary returned by `fetch_metric`, but it has useful additional properties and functions. See `MetricData` class source code for details.

### CODE REVIEW

**Comment by yozik04** [comment]
@slovdahl, take a look. I think, you want to use this new method. That will reduce amount of data reads required to populate entities with values.

```
metric_data.profile
metric_data.next_filter_change_date
metric_data.get_temperature_setting(metric_data.profile)
...
```

**Comment by slovdahl** [comment]
Cool!

I never took a good look at how the library works under the hood 😀 Does calling the old `client.fetch_metrics()` method fetch all the data that the Vallox unit provides? And by using the new API the library will only fetch the data that is actually requested?

**Comment by yozik04** [comment]
Yes `fetch_metrics()` always reads all data. I remember I wanted to implement a separate read for a subset of metrics, but it was never needed. So today after it reads all I just filter out what was requested. `fetch_metric()` -> currently calls `fetch_metrics()` so the same read all is executed.
Same for any other method like `get_profile`, `get_info`, `get_temperature`, `get_fan_speed`, `get_next_filter_change_date`. I would like to deprecate these in future and use only MetricData class for getting values.

**Comment by slovdahl** [comment]
I think I got it to work in HA. But I have so little experience with Python's unit testing and mocking that I cannot figure out how to get the tests to work 🙈 Pushed the current state here: https://github.com/slovdahl/core/commits/bump-vallox-websocket-api-to-4.2.0/

**Comment by yozik04** [comment]
@slovdahl I took a look. It was tough. Here is the result: https://github.com/home-assistant/core/pull/110752
Please review.

**Pull request merged**
